// Terminal - "ctrl + `"
// Множественное редактирование - "ctrl D"
// Множественный курсор - "opt + mouse" 
// Дублировать строку - "shift + opt + down/up"
// Заккоментировать - "cmd + /"
// Проводник - "cmd + B"
// Поиск - "cmd + P"
// Выделить слово - "cmd + D"
// Prettier - "opt + shift + f"